//GENERAMOS UNA INTERFAZ TIPO CONFIGURACION LA CUAL LLEVARA DATOS DE LOS OBJETOS CONFIGURACION
//A LA COLECCION Y AL DOCUMENTO DE FIRESTORE
export interface Configuracion{

  permitirRegistro?:boolean;
}
